### ISSUE TITLE
velbus integration with home assistant failing

### ISSUE THREAD

**Issue by panic1** [Cereal2nd/velbus-aio#22]
In the most recent docker builds for home assistant the velbus integration fails with the following message:

`2021-11-09 12:10:26 WARNING (MainThread) [velbus-packet] UNKNOWN module, you should initialize a full new velbus scan: packet=08:00:00:00:00:00:00, address=246, modules=dict_keys([16, 17, 18, 19, 20, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49])`

**Comment by panic1** [comment]
additional information: the version of velbus-aio in this setup is 2021.11.6

**Comment by Cereal2nd** [comment]
can you clean the velbuscache and then restart hass?

**Comment by panic1** [comment]
No change.  Even started from a fresh, empty config folder and new docker instance, and only did the velbus integration. I'm starting to suspect that I possible have a hardware defect somewhere, although all the modules do seem to be functioning, and a power cycle of the entire velbus installation also didn't resolve it.

**Comment by Cereal2nd** [comment]
can you get me the full log with debug for velbus enabled?

```
logger:
  default: info
  logs:
    velbus-parser: debug
    velbus-module: debug
    velbus-packet: debug
    velbus-protocol: debug
    velbus: debug
    homeassistant.components.velbus: debug
```
